import type {
  Deadline,
  LegalCase,
  User,
} from '@/types/domain.types'

export const demoUser: User = {
  id: 'usr_demo',
  name: 'Dra. Marina Costa',
  email: 'marina@Orbian.demo',
  plan: 'solo',
}

export const cases: LegalCase[] = [
  {
    id: 'case_001',
    title: 'Indenizacao por falha na prestacao de servico',
    caseNumber: '1000928-22.2026.8.26.0100',
    clientName: 'Renata Alves',
    clientPhone: '(11) 99999-1122',
    clientEmail: 'renata@email.com',
    clientCpf: '123.456.789-10',
    area: 'consumidor',
    category: 'Dano Moral',
    flow: 'Especialista em Dano Moral',
    status: 'active',
    progress: 75,
    nextAction: 'Cadastrar prazo',
    nextDeadline: '2026-06-14',
    claimValue: 18000,
    fees: 3000,
    received: 1500,
    pending: 1500,
    expectedProfit: 2600,
    recommendedDocuments: [
      { name: 'RG', received: true },
      { name: 'CPF', received: true },
      { name: 'Comprovante de residencia', received: true },
      { name: 'Contrato ou comprovante', received: false },
      { name: 'Prints e protocolos', received: true },
    ],
    updatedAt: '2026-06-09',
  },
  {
    id: 'case_002',
    title: 'Reclamacao trabalhista por verbas rescisorias',
    caseNumber: '0001842-15.2026.5.02.0031',
    clientName: 'Paulo Mendes',
    clientPhone: '(11) 98888-3344',
    clientEmail: 'paulo@email.com',
    clientCpf: '321.654.987-00',
    area: 'trabalhista',
    category: 'Verbas Rescisorias',
    flow: 'Especialista em Verbas Rescisorias',
    status: 'waiting',
    progress: 40,
    nextAction: 'Atualizar cliente',
    nextDeadline: '2026-06-17',
    claimValue: 42000,
    fees: 6000,
    received: 2000,
    pending: 4000,
    expectedProfit: 5200,
    recommendedDocuments: [
      { name: 'Contrato de trabalho', received: true },
      { name: 'Termo de rescisao', received: false },
      { name: 'Holerites', received: true },
      { name: 'Comprovantes de pagamento', received: false },
    ],
    updatedAt: '2026-06-08',
  },
  {
    id: 'case_003',
    title: 'Acao de cobranca condominial',
    clientName: 'Condominio Jardim Sul',
    clientPhone: '(11) 97777-5566',
    clientEmail: 'sindico@jardimsul.com',
    clientCpf: 'Nao aplicavel',
    area: 'civil',
    category: 'Cobranca',
    flow: 'Especialista em Cobranca',
    status: 'active',
    progress: 65,
    nextAction: 'Solicitar documentos',
    nextDeadline: '2026-06-21',
    claimValue: 12500,
    fees: 2500,
    received: 0,
    pending: 2500,
    expectedProfit: 2100,
    recommendedDocuments: [
      { name: 'Ata de eleicao do sindico', received: true },
      { name: 'Planilha de debitos', received: true },
      { name: 'Convencao condominial', received: false },
      { name: 'Notificacoes enviadas', received: false },
    ],
    updatedAt: '2026-06-07',
  },
]

export const deadlines: Deadline[] = [
  {
    id: 'dl_001',
    caseId: 'case_001',
    caseTitle: cases[0].title,
    title: 'Protocolar emenda da inicial',
    dueDate: '2026-06-14',
    businessDaysLeft: 2,
    priority: 'critical',
    completed: false,
  },
  {
    id: 'dl_002',
    caseId: 'case_002',
    caseTitle: cases[1].title,
    title: 'Enviar documentos complementares',
    dueDate: '2026-06-17',
    businessDaysLeft: 5,
    priority: 'attention',
    completed: false,
  },
  {
    id: 'dl_003',
    caseId: 'case_003',
    caseTitle: cases[2].title,
    title: 'Conferir calculo atualizado',
    dueDate: '2026-06-21',
    businessDaysLeft: 8,
    priority: 'normal',
    completed: false,
  },
]
